MyMVCProject/Controllers/AccountsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using MyMVCProject.Models;
using MyMVCProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyMVCProject.Controllers
{
    public class AccountsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Accounts
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginVM model)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var authManager = HttpContext.GetOwinContext().Authentication;
            var user = userManager.Find(model.Username, model.Password);
            if (user != null)
            {
                var identity = userManager.CreateIdentity(user, DefaultAuthenticationTypes.ApplicationCookie);
                authManager.SignIn(new AuthenticationProperties { IsPersistent = false }, identity);
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Invalid username or password");
            return View(model);
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(RegisterVM model)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            ApplicationUser user = new ApplicationUser { UserName = model.Username };
            var r = userManager.CreateAsync(user, model.Password);
            if (r.Result.Succeeded)
            {
                return RedirectToAction("Login");
            }
            return View(model);
        }
        public ActionResult Logout()
        {
            var authManager = HttpContext.GetOwinContext().Authentication;
            authManager.SignOut();
            return RedirectToAction("Login");
        }
    }
}

MyMVCProject/Controllers/CarTypesController.cs
using ClassLibrary;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyMVCProject.Controllers
{
    [Authorize]
    public class CarTypesController : Controller
    {
        // GET: CarTypes
        CarDbContext db = new CarDbContext();
        public ActionResult Index(int page=1)
        {
            int perPage = 3;
            var data = db.carTypes
                .OrderBy(x => x.TypeId)
                .Skip((page - 1) * perPage)
                .Take(perPage)
                .ToList();
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = (int)Math.Ceiling((double)db.carTypes.Count() / perPage);
            return View(data);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public PartialViewResult Create(CarType ct)
        {
            if (ModelState.IsValid)
            {
                db.carTypes.Add(ct);
                db.SaveChanges();
                return PartialView("_success");
            }
            else
            {
                return PartialView("_fail");
            }
        }
        public ActionResult Edit(int id)
        {
            var data = db.carTypes.First(x => x.TypeId == id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(CarType t)
        {
            if (ModelState.IsValid)
            {
                db.Entry(t).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(t);
        }
        public ActionResult Delete(int id)
        {
            var data = db.carTypes.First(x => x.TypeId == id);
            return View(data);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            if (ModelState.IsValid)
            {
                var ct = new CarType { TypeId = id };
                db.Entry(ct).State = EntityState.Deleted;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(id);
        }

    }
}

MyMVCProject/Controllers/CheckAvailabilitiesController.cs
using ClassLibrary;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyMVCProject.Controllers
{
    [Authorize]
    public class CheckAvailabilitiesController : Controller
    {
        // GET: CheckAvailabilities
        CarDbContext db = new CarDbContext();
        public ActionResult Index()
        {
            return View(db.CheckAvailabilities.ToList());
        }
        [AllowAnonymous]
        public ActionResult Create()
        {
            ViewBag.CarList = db.Cars.ToList();
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Create(CheckAvailability c)
        {
            if (ModelState.IsValid)
            {
                db.CheckAvailabilities.Add(c);
                db.SaveChanges();
                return RedirectToAction("success");
            }
            else
            {
                ModelState.AddModelError("", "Fail to insert.");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            ViewBag.CarList = db.Cars.ToList();
            var data = db.CheckAvailabilities.First(x => x.Id == id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(CheckAvailability c)
        {
            if (ModelState.IsValid)
            {
                db.Entry(c).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(c);
        }
        public ActionResult Delete(int id)
        {
            var data = db.CheckAvailabilities.First(x => x.Id == id);
            return View(data);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            if (ModelState.IsValid)
            {
                var a = new CheckAvailability { Id = id };
                db.Entry(a).State = EntityState.Deleted;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(id);
        }
        [AllowAnonymous]
        public ActionResult success()
        {
            return View();
        }
    }
}

MyMVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -MVC:Project</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <script src="~/Scripts/umd/popper.js"></script>
    <style>
        body {
            padding-top: 70px;
        }
    </style>
    @RenderSection("styles", false)
</head>
<body>
    <div class="navbar navbar-dark bg-success navbar-expand-md fixed-top border-bottom">
        <div class="container">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @Html.ActionLink("ABC Car Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Search&Sort", "GetSearch", "Home", new { }, new { @class = "nav-link" })</li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Expand me!
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Car Types", "Index", "CarTypes", new { }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Cars", "Index", "Cars", new { }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Check Availabilities", "Index", "CheckAvailabilities", new { }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item">@Html.ActionLink("Logout", "Logout", "Accounts", new { }, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        <li class="nav-item">@Html.ActionLink("Login", "Login", "Accounts", new { }, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Register", "Register", "Accounts", new { }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container" style="min-height:440px;">
        @RenderBody()
    </div>
    <hr />
    <footer class="container">
        <div class="card border-light">
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <p class="card-text">&copy;@DateTime.Now.Year, ABC Car Shop</p>
                    </div>
                    <div class="col-6 text-right">
                        <p class="card-text"><i class="fa fa-hand-peace-o" aria-hidden="true"> Md Rashedul Islam</i></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    @RenderSection("scripts", false)
</body>
</html>